FROM ubuntu:20.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

#ENTRYPOINT [ "python3" ]
#CMD [ "app.py" ]
